import streamlit as st

def app():
    with st.container():
        st.title('FOREST DECLASSIFIER MODEL')
        st.header('Data Mining CSE 15 93445 | Finals')
        st.subheader('Team U and X')
        st.write('Alcid, Apalla, Corsino, Cuta, Javier, Langit, Tomelden')
        st.write('')
    with st.container():
        st.header('About the Project')
        st.markdown("Forests have been essential to not just the survival of the earth, but also for humanity and its progress. It is also considered to be a home of multiple species, acting as an ecosystem for many of its inhabitants and is considered to be vital in regulating and cooling the earth’s temperature. However, as humanity’s technological advancement progresses further so do its needs of resources to expand and grow. Throughout the history of mankind, forests have become a staple source of various resources for human beings. Where they may come in different forms such as a source of food from its inhabitants or wood that can be used for shelter or fuel for fire.")
        st.markdown("Deforestation is one of the most common and biggest threats to forests globally and since the 1960s, over half of the tropical forests have been degraded. This resulted in extinction of species for it decreases the ability of forests to provide their needs. This does not only impact animals but also the people whose livelihood depends on forests.")
        st.markdown("According to the World Wide Fund For Nature, the main causes of deforestation today are for the purposes of agriculture, mining and infrastructure projects but it could also be through forest fires. As natural as they are, degraded forests and other factors come into play as to how often forest fires occur. Illegal and unsustainable logging is another cause of deforestation where this act ruins not only nature and wildlife but also communities around these forests.")
        st.markdown("With the development of satellite imagery, it has become possible to track and monitor phenomena such as pollution, climate change, and deforestation. [4]. Millions of historical  satellite images of an area can be used to develop forecasting models to provide predictions about the area. By being able to recognize areas that are currently undergoing environmental degradation or areas at risk of deforestation, human intervention could be pushed onto those areas to prevent further damage.")
        st.markdown("Satellite imagery has been used by environmentalists and scientists to study and record the progress of deforestation over the years. Various studies on deforestation have conducted the use of satellite imagery in their research.")
        st.markdown("The driving motivation for the study will focus on assisting in the preservation of large forested areas and help in reducing humanity’s carbon footprint by detecting deforestation-related zones and placing those areas in higher priority to restore and preserve for new forests to develop.")
    with st.container():
        st.header('Significance of the Study')
        st.markdown("Agriculture and farmlands have become even more significant in recent decades because of humanity’s growing population and heightened birth rates. Due to the need for expanding land, forests have decreased since they are more seen as an obstruction for farmlands and are immediately felled and sold as lumber. In addition to the rising demand for timber and land, illegal deforestation has become an increasing problem, significantly in the Brazilian Amazon. Because of multiple accounts of deforestation, government officials and climate activists have had immense difficulty detecting deforestation in larger land areas.")
        st.markdown("Fortunately, with the vast technological innovations at our disposal, we can readily use available satellite imagery datasets which can provide unbiased insights into the state of the Earth's natural landscape from mining areas, urban infrastructure, and weathering. These results can become a frequent basis for setting priorities towards moving forward with environmental policies and recognizing empirical evidence provided by remote sensing satellite imagery for sustainability purposes.")
        st.markdown("This project then aims to provide a solution for detecting deforestation from satellite imagery through modern methods found in data mining. In particular, this study is intended for the concurrent efforts of environmental organizations and government departments that plan to find ways of predicting deforestation and leading reforestation. Researchers who plan to integrate this project for related environmental efforts for wildlife protection and natural ecosystems can also benefit by improving the output model and application using their local data or better machine learning algorithms. The results of this project will then help provide essential information on how computer vision through machine learning models can be used to identify causes of deforestation coming from satellite imagery and help reforestation efforts identify the cause of deforestation and alleviate it.")

